services:
  api:
    build:
      context: ./src/Api
      dockerfile: Dockerfile
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=db;Database=AppDb;User Id=sa;Password=SomePassword123;TrustServerCertificate=True;
    ports:
      - "5001:8080"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - db
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SomePassword123   # Used for local development only
    volumes:
      - app_db_data:/var/opt/mssql
    ports:
      - "1433:1433"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: app-network

volumes:
  app_db_data:
    driver: local